### ISSUE TITLE
Error: 'add_binding_callback' is not exported from svelte/internal

### ISSUE THREAD

**Issue by kenanchristian** [ValentinH/svelte-easy-crop#3]
Hi, I was trying to add this to my svelte app but I got this error when trying to run the `dev` npm script. 

```
bundles src/main.js → public/build/bundle.js...
[!] Error: 'add_binding_callback' is not exported by node_modules/svelte/internal/index.mjs, imported by node_modules/svelte-easy-crop/dist/index.mjs
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/svelte-easy-crop/dist/index.mjs (1:127)
1: import { SvelteComponent, init, safe_not_equal, element, append, set_style, toggle_class, insert, detach, space, attr, listen, add_binding_callback, noop, run_all } from 'svelte/internal';
                                                                                                                                  ^
2: import { createEventDispatcher, onMount, onDestroy } from 'svelte';
Error: 'add_binding_callback' is not exported by node_modules/svelte/internal/index.mjs, imported by node_modules/svelte-easy-crop/dist/index.mjs
    at error (/Users/kenanchristian/Documents/projects/svelte-app/node_modules/rollup/dist/shared/rollup.js:217:30)
    at Module.error (/Users/kenanchristian/Documents/projects/svelte-app/node_modules/rollup/dist/shared/rollup.js:15145:16)
    at handleMissingExport (/Users/kenanchristian/Documents/projects/svelte-app/node_modules/rollup/dist/shared/rollup.js:15042:28)
    at Module.traceVariable (/Users/kenanchristian/Documents/projects/svelte-app/node_modules/rollup/dist/shared/rollup.js:15520:24)
    at ModuleScope.findVariable (/Users/kenanchristian/Documents/projects/svelte-app/node_modules/rollup/dist/shared/rollup.js:14199:39)
    at FunctionScope.findVariable (/Users/kenanchristian/Documents/projects/svelte-app/node_modules/rollup/dist/shared/rollup.js:9663:38)
    at ChildScope.findVariable (/Users/kenanchristian/Documents/projects/svelte-app/node_modules/rollup/dist/shared/rollup.js:9663:38)
    at FunctionScope.findVariable (/Users/kenanchristian/Documents/projects/svelte-app/node_modules/rollup/dist/shared/rollup.js:9663:38)
    at ChildScope.findVariable (/Users/kenanchristian/Documents/projects/svelte-app/node_modules/rollup/dist/shared/rollup.js:9663:38)
    at Identifier$1.bind (/Users/kenanchristian/Documents/projects/svelte-app/node_modules/rollup/dist/shared/rollup.js:10080:40)
```

I'm using the svelte default template, and only adding `svelte-preprocess` to compile sass stylesheet, and added a babel config with babel-preset-env.

**Comment by kenanchristian** [comment]
Oh sorry, this is my fault.
I'm importing it like this for some reason (probably autocomplete)
```
import Cropper from 'svelte-easy-crop/dist/index'
```
Instead of the one in the readme, which looks like this
```
import Cropper from 'svelte-easy-crop'
```
